# Generated by Django 2.2.7 on 2019-11-24 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191124_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='hyperlink',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hyperlink',
            name='url',
            field=models.URLField(max_length=2048),
        ),
    ]
