# Generated by Django 2.2.7 on 2019-11-24 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191124_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='HyperlinkAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=2048)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('hyperlink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Hyperlink')),
            ],
        ),
    ]
