# Generated by Django 2.2.7 on 2019-11-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hyperlinkalias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyperlinkalias',
            name='alias',
            field=models.CharField(max_length=2048, unique=True),
        ),
    ]
