# Generated by Django 2.2.7 on 2019-11-24 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191124_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='HyperlinkView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('viewed_on', models.DateTimeField(auto_now_add=True)),
                ('hyperlink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Hyperlink')),
                ('hyperlink_alias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.HyperlinkAlias')),
            ],
        ),
    ]
